export function obterCategorias() {
  return [
    {
      nome: 'Laticínios e Ovos',
      ingredientes: [
        'Ovos',
        'Queijo',
        'Leite',
        'Manteiga',
        'Creme de Leite',
        'Iogurte',
        'Leite Condensado',
        'Sorvete'
      ],
      rotulo: 'laticinios_e_ovos'
    },
    {
      nome: 'Farinhas e Fermentos',
      ingredientes: [
        'Farinha de trigo',
        'Polvilho',
        'Farinha de rosca',
        'Canjica',
        'Farinha de mandioca',
        'Fubá',
        'Linhaça',
        'Fermento químico'
      ],
      rotulo: 'farinhas_e_fermentos'
    },
    {
      nome: 'Carnes',
      ingredientes: [
        'Carne de boi',
        'Carne de porco',
        'Carne de frango',
        'Carne de peixe',
        'Carne de cordeiro'
      ],
      rotulo: 'carnes'
    },
    {
      rotulo: 'cereais_e_graos',
      nome: 'Vegetais',
      ingredientes: [
        'Tomate',
        'Cenoura',
        'Beterraba',
        'Abóbora',
        'Brócolis',
        'Couve-flor',
        'Ervilha',
        'Milho',
        'Batata',
        'Batata-doce',
        'Mandioca',
        'Mandioquinha',
        'Chuchu',
        'Abobrinha',
        'Berinjela',
        'Pimentão',
        'Quiabo',
        'Vagem',
        'Repolho',
        'Alface',
        'Rúcula',
        'Agrião',
        'Espinafre',
        'Acelga',
        'Almeirão',
        'Chicória',
        'Salsinha',
        'Cebolinha',
        'Coentro',
        'Manjericão',
        'Hortelã',
        'Alecrim',
        'Orégano',
        'Sálvia',
        'Tomilho',
        'Pimenta',
        'Gengibre',
        'Cebola',
        'Alho',
        'Pimenta',
        'Pimenta-do-reino',
        'Pimenta-calabresa',
        'Pimenta-dedo-de-moça',
        'Pimenta-malagueta',
        'Pimenta-biquinho',
        'Pimenta-jalapeño',
        'Pimenta-habanero',
        'Pimenta-murupi',
        'Pimenta-cumari',
        'Pimenta-rosa',
        'Pimenta-branca',
        'Pimenta-verde',
        'Pimenta-amarela',
        'Pimenta-vermelha',
        'Pimenta-laranja',
        'Pimenta-roxa',
        'Pimenta-azul',
        'Pimenta-preta',
        'Pimenta-brasileira',
        'Pimenta-italiana',
        'Pimenta-argentina',
        'Pimenta-mexicana',
        'Pimenta-chilena',
        'Pimenta-peruana',
        'Pimenta-colombiana',
        'Pimenta-venezuelana',
        'Pimenta-uruguaia',
        'Pimenta-paraguaia',
        'Pimenta-argelina',
        'Pimenta-marroquina',
        'Pimenta-tunisiana',
        'Pimenta-egípcia',
        'Pimenta-sudanesa',
        'Pimenta-etíope',
        'Pimenta-somali',
        'Pimenta-eritreia',
        'Pimenta-djibuti',
        'Pimenta-ruandesa',
        'Pimenta-burundesa',
        'Pimenta-ugandense',
        'Pimenta-queniana',
        'Pimenta-tanzaniana',
        'Pimenta-moçambicana',
        'Pimenta-malgaxe',
        'Pimenta-seichelense',
        'Pimenta-comorense',
        'Pimenta-mauriciana',
        'Pimenta-sul-africana',
        'Pimenta-namibiana',
        'Pimenta-angolana',
        'Pimenta-zambiana',
        'Pimenta-z'
      ]
    }
  ]
}
